resources:
- name: resource-test-pipeline
  type: git
  source:
    uri: https://github.com/adriengentil/test-concourse-pipeline.git
    branch: master

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: resource-test-pipeline
        trigger: true
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: find
            args:
              - "/"
      - set_pipeline: self
        file: test-concourse-pipeline/pipeline.yml
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [hello world]
