resources:
- name: resource-test-pipeline
  type: git
  source:
    uri: https://github.com/adriengentil/test-concourse-pipeline.git

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: resource-test-pipeline
        trigger: true
      - set_pipeline: test-pipeline
        file: resource-test-pipeline/pipeline.yml
      - task: hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [hello]
      - task: world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [world]
      - task: "!!!"
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: ["!!!"]
